"""Добавлены поля в таблицу responses

Revision ID: bc2de3564828
Revises: 29f7f4145030
Create Date: 2025-04-29 19:10:45.397318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2de3564828'
down_revision = '29f7f4145030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('message', sa.String(), nullable=False, comment='Сопроводительное письмо'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    # ### end Alembic commands ###
